{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "opensearch-operator.fullname" . }}-validating-webhook-configuration
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "opensearch-operator.fullname" . }}-serving-cert
  {{- end }}
webhooks:
- name: vopensearchactiongroup.opensearch.dremio.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "opensearch-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-opensearch-dremio-io-v1-opensearchactiongroup
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  rules:
  - apiGroups:
    - opensearch.dremio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchactiongroups
  sideEffects: None
- name: vopensearchcluster.opensearch.dremio.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "opensearch-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-opensearch-dremio-io-v1-opensearchcluster
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  rules:
  - apiGroups:
    - opensearch.dremio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchclusters
  sideEffects: None
- name: vopensearchcomponenttemplate.opensearch.dremio.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "opensearch-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-opensearch-dremio-io-v1-opensearchcomponenttemplate
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  rules:
  - apiGroups:
    - opensearch.dremio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchcomponenttemplates
  sideEffects: None
- name: vopensearchindextemplate.opensearch.dremio.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "opensearch-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-opensearch-dremio-io-v1-opensearchindextemplate
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  rules:
  - apiGroups:
    - opensearch.dremio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchindextemplates
  sideEffects: None
- name: vopensearchismpolicy.opensearch.dremio.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "opensearch-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-opensearch-dremio-io-v1-opensearchismpolicy
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  rules:
  - apiGroups:
    - opensearch.dremio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchismpolicies
  sideEffects: None
- name: vopensearchrole.opensearch.dremio.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "opensearch-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-opensearch-dremio-io-v1-opensearchrole
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  rules:
  - apiGroups:
    - opensearch.dremio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchroles
  sideEffects: None
- name: vopensearchsnapshotpolicy.opensearch.dremio.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "opensearch-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-opensearch-dremio-io-v1-opensearchsnapshotpolicy
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  rules:
  - apiGroups:
    - opensearch.dremio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchsnapshotpolicies
  sideEffects: None
- name: vopensearchtenant.opensearch.dremio.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "opensearch-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-opensearch-dremio-io-v1-opensearchtenant
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  rules:
  - apiGroups:
    - opensearch.dremio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchtenants
  sideEffects: None
- name: vopensearchuser.opensearch.dremio.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "opensearch-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-opensearch-dremio-io-v1-opensearchuser
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  rules:
  - apiGroups:
    - opensearch.dremio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchusers
  sideEffects: None
- name: vopensearchuserrolebinding.opensearch.dremio.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "opensearch-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-opensearch-dremio-io-v1-opensearchuserrolebinding
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  rules:
  - apiGroups:
    - opensearch.dremio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchuserrolebindings
  sideEffects: None
{{- end }}

