apiVersion: v2
name: spark-kubeflow-playground
description: Kubeflow Spark Operator for the data playground
type: application
version: 1.0.0
appVersion: "2.4.0"

dependencies:
  - name: spark-operator
    version: "2.4.0"
    repository: "https://kubeflow.github.io/spark-operator"
