# ObjectBucketClaim â€” Rook operator creates the bucket "iceberg-upload" in RGW
# Also creates Secret + ConfigMap named "iceberg-upload" in same namespace
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: iceberg-upload
  namespace: rook-ceph
spec:
  bucketName: iceberg-upload
  storageClassName: ceph-bucket
