apiVersion: v2
name: spark-apache-playground
description: Apache Spark Kubernetes Operator for the data playground
type: application
version: 1.0.0
appVersion: "0.7.0"

dependencies:
  - name: spark-kubernetes-operator
    version: "1.5.0"
    repository: "https://apache.github.io/spark-kubernetes-operator"
