# KnativeEventing CR â€” the Knative Operator reconciles this into a full Eventing deployment
# Includes: Kafka source support
# Docs: https://knative.dev/docs/install/operator/configuring-eventing-cr/
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  version: "1.21.0"
  source:
    kafka:
      enabled: true
  config:
    br-defaults:
      default-br-config: |
        clusterDefault:
          brokerClass: Kafka
          apiVersion: v1
          kind: ConfigMap
          name: kafka-broker-config
          namespace: knative-eventing
